fixtures:
  fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.17.0"
    concat: 
      repo: "puppetlabs/concat"
      ref:  "2.2.1"
  symlinks:
    ldirectord: "#{source_dir}"
