image: "ruby:2.5"

cache:
  paths:
    - vendor/ruby
    - spec/fixtures

before_script:
  - gem install bundler  --no-ri --no-rdoc
  - PUPPET_VERSION=3.8.7 bundle install -j $(nproc) --path vendor

test-validate:
  stage: test
  tags:
   - puppet-modules
  script:
  - bundle exec rake validate

test-lint:
  stage: test
  tags:
   - puppet-modules
  script:
  - bundle exec rake lint

test-rspec-parser-current:
  stage: test
  tags:
   - puppet-modules
  script:
  - bundle exec rake spec
  coverage: '/Resource coverage: \d+\.\d+/'

test-rspec-parser-future:
  stage: test
  tags:
   - puppet-modules
  script:
  - PARSER=future bundle exec rake spec
  coverage: '/Resource coverage: \d+\.\d+/'

